# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bdd5b915251f99ce6e3051c8bf2481571249b9c39e4b34e3636d3b92ca5863c99a014dcb3d002d90d71f6919c13d9368b1a5c2d3b20fb6167e9cbdcdef26b7a8

test:
  secret_key_base: e30952084fb1be7aa0841ac089cfea150a747261025dae54101c21e00855aece1fbcff34538c0a72cb6deac9f6a331871828f3e1aaf7d38bf425dbf22660d9ef

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
